@startuml
[*] -->CPU2
[*]-->CPU1

state CPU1{
    寄存器1 --> 高速多级缓存1
    高速多级缓存1-->寄存器1
}

state CPU2{
寄存器2 --> 高速多级缓存2
高速多级缓存2-->寄存器2
}

state 高速多级缓存1{
高速多级缓存1-->主内存RAM
主内存RAM-->高速多级缓存1
}

state 高速多级缓存2{
高速多级缓存2-->主内存RAM
主内存RAM-->高速多级缓存2
}

state 主内存RAM{

}

主内存RAM -->[*]



@enduml